### ISSUE TITLE
Note and Warning blocks

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb-docs#1]
With the new web docs we have the possibility to create

.. note:
   Note blocks

and

.. warning
   Warning blocks

The note blocks were all created manually after the pandoc conversion. I've added some warning blocks as well. But we should check, if there can be more warnings or if some note blocks are too big and should better be part of the normal text.

**Comment by yaozhihang** [comment]
Thanks, resolved in master branch.
