### ISSUE TITLE
Numbering for figures and tables

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb-docs#13]
For the online docs it doesn't make too much sense to use global sequences for figures and tables. However, for a PDF export of the whole document it would be good to have it. Find a way to make this possible with ReadTheDocs.

**Comment by FxKu** [comment]
For referecing figures, this [thread](https://stackoverflow.com/questions/2686310/referencing-figures-with-numbers-in-sphinx-and-restructuredtext) looks helpful.

Some infos from the [manual](http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure).

**Comment by yaozhihang** [comment]
Thanks for the helpful link and info. It works very well.
