### ISSUE TITLE
Tables are not properly rendered in PDF version

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb-docs#19]
There are two small problems: 
1. Tables spanning multiple pages are not properly displayed (see: p.89 and p90)
2. The size of table cell is not automatically adjusted according to the text length. (see p.10)

A PDF version of the 3dcitydb-docs can be downloaded from here:
https://3dcitydb-docs.readthedocs.io/_/downloads/en/release-v4.2.3/pdf/

@Son-HNguyen would you like to look into this issue?

**Comment by clausnagel** [comment]
Closing this issue. PDF output was removed due to multiple issues when compiling the PDF.

**Comment by Son-HNguyen** [comment]
Thanks, I forgot to comment that I was able to fix some tables for the PDF version but it was very much time consuming.
