### ISSUE TITLE
Document Docker Networks

### ISSUE THREAD

**Issue by bkuster** [3dcitydb/3dcitydb-docs#29]
# Issue
Currently, the docs advise to use the deprecated `--link` to create a bridged network.

# Solution
Document the use of custom networks, e.g:
```bash
docker network create citydb
docker run -d --name citydb --nework citydb -e ...
```

**Comment by BWibo** [comment]
Thx, fixed in https://github.com/3dcitydb/3dcitydb-docs/commit/de8d20a55a573913c28b1956d10a952cd4c60854.

**Comment by clausnagel** [comment]
@BWibo, the [WFS Docker chapter](https://3dcitydb-docs.readthedocs.io/en/latest/wfs/docker.html) still uses `--link`. Could you please adapt this chapter as well?

**Comment by BWibo** [comment]
Thx, I missed that. Fixed in https://github.com/3dcitydb/3dcitydb-docs/commit/056d6d8744b3706180de619164f25213ba95bb64.
