### ISSUE TITLE
Cross chapter references

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb-docs#3]
The current documentation includes many cross chapter references. In an online documentation they are not so helpful and should at least include links to corresponding file + section.

We should still use the name of the "chapter", though, in case somebody exports all the docs to a PDF. Not sure, if we just drop the chapter number (don't know how Sphinx does numbering).

**Comment by Son-HNguyen** [comment]
[This answer](https://stackoverflow.com/questions/15394347/adding-a-cross-reference-to-a-subheading-or-anchor-in-another-page/19543591#19543591) may be useful.

**Comment by yaozhihang** [comment]
Thanks, resolved in master branch.
