### ISSUE TITLE
make file for Linux

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb-docs#32]
According to the README.md there should be a `make` file for Linux, but I can only find the `make.bat` for Windows. Or is the `Makefile` meant to be used?

**Comment by BWibo** [comment]
No, the name of the program that is used is [`make`](https://linux.die.net/man/1/make) and the `Makefile` contains the instruction it uses. It is usually available on Unix systems, if not it can be installed from packages, e.g. `apt install make` or `apt install build-essential`. I'll add a hint on how to install `make` if it is missing.

**Comment by BWibo** [comment]
Resolved in https://github.com/3dcitydb/3dcitydb-docs/commit/605999261b878b286611dcae1f5290da644ed4aa.
