### ISSUE TITLE
Released version 4.1

### ISSUE THREAD

**Issue by mulfvik** [3dcitydb/3dcitydb-docs#33]
The online docs, latest, refers to version 4.2 of 3DCityDB but the latest release is 4.1.
...or is the docs for future releases published already? Sorry for being stupid

**Comment by clausnagel** [comment]
The `latest` version is automatically created from the master branch and, thus, always contains the most up to date content. 

Whenever the development of a new feature for one of the 3DCityDB components (such as database schema, Importer/Exporter, WFS) has been completed, we document the new feature and merge the new documentation into master. This is when `latest` gets updated automatically. So, `latest` does not point to most recent release but rather reflects the next upcoming release. I agree that this is confusing. Maybe `edge` would be a better version label than `latest` for this purpose.

I am not sure whether we can change this behaviour (see [readthedocs documentation](https://docs.readthedocs.io/en/stable/versions.html)). But it seems that readthedocs offers a `stable` label to point to the most recent release. We will check how to make this available.
