### ISSUE TITLE
Heading styles

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb-docs#6]
The docx conversion produced many different heading styles starting.
chapter: =====
subchapter: -----
subsubchapter: ~~~~~
section: ^^^^^
subsection: ''''

I left most of them unchanged (except for subsection), but have seen that it's also common to use === at the top of each file. Not sure, how it then turns out if somebody wants to creates one PDF document out of it. Hopefully the structure of folders and `index.rst` files takes care of correct alignment and numbering. [Here](https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings) is how Sphinx handles headings.

**Comment by yaozhihang** [comment]
It seems that the heading styles produced by the conversion works well for the both HTML and PDF versions.
