### ISSUE TITLE
docs structure and file names

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb-docs#8]
The pandoc conversion of the original docx document produced only one rst file. The whole split up into files has been done by me on behalf what I thought makes sense. Not too long documents and subfolders where there were many subsections.

There are some general changes that need to be discussed, though. The current structure is as follows:

1. intro folder: Online docs should have a first steps chapter that jumps straight at using the software. First, I thought, I have to write something up, but then I found that chapter 3 from the documentation serves this purpose quite well. I have also included the Docker chapter in the intro folder.
2. `3dcitydb` folder: This one contains chapter 1, 2 and 4 from the docx version.
3. `impexp` folder: Contains 5 and 6.
4. `wfs` folder: unchanged
5. `webmap` folder: unchanged (split up the big features chapter to multiple files)
6. appendix stuff is part of the main source directory

Sometimes, I changed some headings as they where quite long in the original document (like "Running and using the Importer/Exporter" --> "Interfaces"). I kept the names of the rst files very short. I used names twice and more, but within the folders it should make sense, I think.

Anyway, feel free to give feedback.

**Comment by yaozhihang** [comment]
The structure is good and has been adopted for the [release 4.2.3](https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/).
